extends "res://scenes/world/HuntingGround.gd"
## 던전 전투방 (generated by tools/gen_dungeon_tscn.py). Same geometry and wave
## plumbing as a hunting ground, but waves are FINITE: clear them all and the
## spiked gate to the next room opens. Drops accumulate in GameState's run
## satchel (런 정산형) instead of the wallet — see GameState.start_dungeon_run.
## Re-entering a room re-locks it (per-visit state, like the boss arena respawn).

# Fixed dungeon-dweller id for this room (skeleton/bat/slime_red), instead of
# the hunt's stage->id table.
@export var mon_id: String = "skeleton"

var _waves_done: int = 0

func _ready() -> void:
	super()
	# Gate starts closed: north exit unusable until every wave is cleared.
	$ExitNorth/Interact.set_active(false)

func _monster_id() -> String:
	return mon_id

func _wave_size() -> int:
	return GameConfig.DUNGEON_MONSTERS_PER_WAVE

## Finite-wave override: spawn the next wave until the room quota is met, then
## open the gate instead of respawning forever.
func _on_wave_cleared() -> void:
	_waves_done += 1
	if _waves_done < GameConfig.DUNGEON_WAVES_PER_ROOM:
		_banner.text = "웨이브 클리어! (%d/%d)" % [_waves_done, GameConfig.DUNGEON_WAVES_PER_ROOM]
		_banner.visible = true
		await get_tree().create_timer(RESPAWN_DELAY).timeout
		if is_instance_valid(self) and is_inside_tree() and _respawning:
			_spawn_wave()
	else:
		_open_gate()

## Spikes sink into the floor (frame 0 = raised -> 3 = stubs), the blocker
## collider turns off, and the north exit becomes usable.
func _open_gate() -> void:
	_banner.text = "관문이 열렸다!"
	_banner.visible = true
	Audio.play("door")
	$ExitNorth/Interact.set_active(true)
	for seg in [$Gate/SegL, $Gate/SegR]:
		create_tween().tween_property(seg, "frame", 3, 0.45)
	$Gate/Body/Col.set_deferred("disabled", true)
	await get_tree().create_timer(1.4).timeout
	if is_instance_valid(self) and is_inside_tree():
		_banner.visible = false
