extends Node2D
## A hunting ground in the northward chain (사냥터1/2/3 — generated by
## tools/gen_hunt_tscn.py). Each map has a FIXED monster stage; a wave of
## monsters sits in the field and the player kills them for gold + a chance at
## a Whetstone. Road-end exits (invisible Interactables) link the chain:
## ExitSouth -> prev_scene (town for map 1), ExitNorth -> next_scene ("" = dead
## end on the deepest map). Killed waves auto-respawn after a short delay.

# Per-stage monster id (resolved to battler sheets inside Monster.gd).
const STAGE_ID := {1: "slime", 2: "goblin", 3: "orc", 4: "ogre", 5: "cyclops"}
const MONSTER := preload("res://scenes/actors/Monster.tscn")
const COIN_TEX := preload("res://assets/items/coin.png")
const MAT_TEX := preload("res://assets/items/material.png")

# Map bounds (32px world, 21x33 tiles portrait) — used for the camera limits.
const MAP_W: int = 672
const MAP_H: int = 1056

# Fixed spawn anchors flanking the vertical road (mirrors gen_hunt_tscn.py
# ANCHORS; decor scatter keeps clear of these). Jittered per spawn.
const ANCHORS: Array[Vector2] = [
	Vector2(150, 220), Vector2(480, 200), Vector2(140, 420), Vector2(500, 440),
	Vector2(160, 640), Vector2(490, 620), Vector2(150, 820), Vector2(500, 840),
]

# Delay before the next wave auto-spawns, so the death animation can play out.
const RESPAWN_DELAY: float = 0.8

const NEXT_SPAWN := "from_south"   # entering deeper -> appear at the south end

@export_range(1, 5) var stage: int = 1
@export var aggressive: bool = false           # monsters charge on proximity (사냥터3)
@export var monster_speed: float = 1.0         # pace multiplier (사냥터3 runs hotter)
@export_file("*.tscn") var prev_scene: String = ""
@export_file("*.tscn") var next_scene: String = ""   # "" = dead end
@export var prev_spawn: String = "from_hunt"   # marker to use in prev_scene

var _respawning: bool = false

@onready var _monsters: Node2D = $Monsters
@onready var _banner: Label = $Overlay/Banner

func _ready() -> void:
	$ExitSouth/Interact.interacted.connect(_go_prev)
	if next_scene != "":
		$ExitNorth/Interact.interacted.connect(_go_next)
	_banner.visible = false
	# Keep the camera inside the forest (the canopy border hides the map edge).
	SceneManager.setup_camera($Player/Camera2D, MAP_W, MAP_H, 0.7)
	_spawn_wave()

func _go_prev() -> void:
	SceneManager.goto(prev_scene, prev_spawn)

func _go_next() -> void:
	SceneManager.goto(next_scene, NEXT_SPAWN)

# ---------------------------------------------------------------------------
# Waves
# ---------------------------------------------------------------------------
func _spawn_wave() -> void:
	_respawning = false
	for c in _monsters.get_children():
		c.queue_free()
	var mon_id: String = _monster_id()
	for i in mini(_wave_size(), ANCHORS.size()):
		var m := MONSTER.instantiate()
		_monsters.add_child(m)
		m.position = ANCHORS[i] + Vector2(randf_range(-16, 16), randf_range(-16, 16))
		m.setup(stage, mon_id)
		m.aggressive = aggressive
		m.speed_mult = monster_speed
		m.died.connect(_on_killed.bind(m))
	_banner.visible = false

# Template hooks — DungeonRoom overrides these for fixed monster ids, smaller
# waves, and a finite wave count that opens the gate instead of respawning.
func _monster_id() -> String:
	return STAGE_ID.get(stage, "slime")

func _wave_size() -> int:
	return GameConfig.MONSTERS_PER_WAVE

## Called once per cleared wave (guarded by _respawning). Default hunt behavior:
## banner + short delay + endless respawn.
func _on_wave_cleared() -> void:
	_banner.text = "웨이브 클리어!"
	_banner.visible = true
	await get_tree().create_timer(RESPAWN_DELAY).timeout
	if is_instance_valid(self) and is_inside_tree() and _respawning:
		_spawn_wave()

func _on_killed(_stage: int, m: Node) -> void:
	var pos: Vector2 = (m as Node2D).global_position
	# Rewards drop as ground pickups (rest ~2s, then vacuum into the player);
	# gold/whetstone are granted when a pickup reaches them, not on the kill.
	var drop: Dictionary = GameState.roll_monster_drop(stage)
	_spawn_pickup(COIN_TEX, {"gold": drop["gold"], "material": false}, pos)
	if drop["material"]:
		_spawn_pickup(MAT_TEX, {"gold": 0, "material": true}, pos + Vector2(0, 6))
	# When the last monster of the wave dies, hand off to the wave-cleared hook.
	# Counting via is_alive (not tree membership): corpses linger in the tree
	# while fading, so simultaneous kills (one swing hitting several monsters)
	# would otherwise leave the count > 0 forever and the wave stuck.
	if _alive_count() == 0 and not _respawning:
		_respawning = true
		_on_wave_cleared()

func _alive_count() -> int:
	var n: int = 0
	for c in _monsters.get_children():
		if not c.is_queued_for_deletion() \
				and (not c.has_method("is_alive") or c.is_alive()):
			n += 1
	return n

# ---------------------------------------------------------------------------
# Drop pickups
# ---------------------------------------------------------------------------
func _spawn_pickup(icon: Texture2D, payload: Dictionary, pos: Vector2) -> void:
	var p := DropPickup.new()
	add_child(p)
	p.global_position = pos
	p.setup(icon, payload, $Player)
	p.collected.connect(_on_drop_collected)

## A pickup reached the player: grant the payload and float the +text above them.
func _on_drop_collected(drop: Dictionary) -> void:
	GameState.grant_monster_drop(drop)
	var player: Node2D = $Player
	if int(drop["gold"]) > 0:
		_floating_text(player.global_position + Vector2(0, -30),
			"+%s G" % _comma(int(drop["gold"])), Color(1, 0.95, 0.5))
	if drop["material"]:
		_floating_text(player.global_position + Vector2(0, -42),
			"+%s!" % GameConfig.MATERIAL_LABEL, Color(0.8, 0.6, 1))

# ---------------------------------------------------------------------------
# Floating text (world-space, rises and fades)
# ---------------------------------------------------------------------------
func _floating_text(world_pos: Vector2, text: String, color: Color) -> void:
	var l := Label.new()
	l.text = text
	l.global_position = world_pos + Vector2(-12, 0)
	l.add_theme_font_size_override("font_size", 9)
	l.add_theme_color_override("font_color", color)
	l.z_index = 50
	l.visibility_layer = 2  # actor layer: culled from the minimap render
	add_child(l)
	var tw := create_tween()
	tw.set_parallel(true)
	tw.tween_property(l, "global_position:y", world_pos.y - 22.0, 0.7)
	tw.tween_property(l, "modulate:a", 0.0, 0.7)
	tw.chain().tween_callback(l.queue_free)

static func _comma(n: int) -> String:
	var s := str(abs(n))
	var out := ""
	var c := 0
	for i in range(s.length() - 1, -1, -1):
		out = s[i] + out
		c += 1
		if c % 3 == 0 and i > 0:
			out = "," + out
	return ("-" if n < 0 else "") + out
